const id=new URLSearchParams(location.search).get("id");let project=null;const preview=document.querySelector("#preview");
async function init(){if(!id)return location.href="/dashboard.html";const r=await fetch("/api/projects/"+id),x=await r.json();if(!r.ok)return alert(x.error);project=x.project;render()}
function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function render(){document.querySelector("#title").textContent=project.name;document.querySelector("#primary").value=project.theme?.primary||"#7c3aed";document.querySelector("#background").value=project.theme?.background||"#fff";const t=project.theme||{},p=project.pages?.[0]||{blocks:[]};let h=`<div style="font-family:Inter,Arial;color:${t.text||"#111827"};background:${t.background||"#fff"};min-height:100%"><nav style="padding:20px 7%;display:flex;justify-content:space-between;border-bottom:1px solid #eee"><strong>${esc(project.name)}</strong><a href="#contato" style="color:${t.primary||"#7c3aed"}">Contato</a></nav>`;for(const b of p.blocks||[]){if(b.type==="hero")h+=`<section style="padding:100px 7%;text-align:center;background:linear-gradient(135deg,${t.primary||"#7c3aed"},${t.secondary||"#111827"});color:#fff"><h1 style="font-size:clamp(40px,7vw,72px)">${esc(b.title)}</h1><p>${esc(b.subtitle)}</p><a style="display:inline-block;background:#fff;color:${t.primary||"#7c3aed"};padding:13px 22px;border-radius:9px;font-weight:800" href="${esc(b.buttonUrl||"#")}">${esc(b.buttonText||"Saiba mais")}</a></section>`;else if(b.type==="about")h+=`<section style="padding:70px 7%;text-align:center"><h2>${esc(b.title)}</h2><p>${esc(b.text)}</p></section>`;else if(["services","products","testimonials"].includes(b.type)){h+=`<section style="padding:70px 7%"><h2 style="text-align:center">${esc(b.title)}</h2><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:18px">`;for(const i of b.items||[])h+=`<article style="border:1px solid #e5e7eb;padding:22px;border-radius:14px"><h3>${esc(i.title||i.name)}</h3><p>${esc(i.text)}</p>${i.price?`<b>${esc(i.price)}</b>`:""}</article>`;h+="</div></section>"}else if(b.type==="contact")h+=`<section id="contato" style="padding:70px 7%;text-align:center"><h2>${esc(b.title)}</h2><p>${esc(b.text)}</p><p>${esc(project.settings?.whatsapp||"")}</p><p>${esc(project.settings?.instagram||"")}</p></section>`;else if(b.type==="cta")h+=`<section style="padding:70px 7%;text-align:center;background:${t.primary||"#7c3aed"};color:#fff"><h2>${esc(b.title)}</h2><p>${esc(b.text)}</p></section>`}preview.innerHTML=h+`<footer style="padding:30px;text-align:center;background:${t.secondary||"#111827"};color:#fff">Site criado com SiteForge AI</footer></div>`}
async function save(){const r=await fetch("/api/projects/"+id,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({project})});if(!r.ok)alert((await r.json()).error);else alert("Salvo!")}
document.querySelector("#save").onclick=save;
document.querySelector("#ai").onclick=async()=>{const command=document.querySelector("#command").value.trim();if(!command)return alert("Digite uma alteração.");const b=document.querySelector("#ai");b.disabled=true;b.textContent="⏳ IA...";try{const r=await fetch("/api/ai/edit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({project,command})});const x=await r.json();if(!r.ok)throw Error(x.error);project=x.project;document.querySelector("#command").value="";render()}catch(e){alert(e.message)}finally{b.disabled=false;b.textContent="Aplicar com IA"}};
document.querySelector("#theme").onclick=()=>{project.theme=project.theme||{};project.theme.primary=document.querySelector("#primary").value;project.theme.background=document.querySelector("#background").value;render()};
document.querySelector("#publish").onclick=async()=>{await save();const r=await fetch("/api/projects/"+id+"/publish",{method:"POST"}),x=await r.json();if(!r.ok)return alert(x.error);alert(x.url)};
document.querySelector("#desk").onclick=()=>preview.classList.remove("mobile");document.querySelector("#mob").onclick=()=>preview.classList.add("mobile");
document.querySelector("#export").onclick=()=>{const a=document.createElement("a"),b=new Blob(["<!doctype html>"+preview.innerHTML],{type:"text/html"});a.href=URL.createObjectURL(b);a.download="siteforge-site.html";a.click()};
init();